bump_version: null
lint:
  actions_ci: false
nf_core_version: 3.0.1
org_path: null
repository_type: pipeline
template:
  author: Adam Bennett
  description: A workflow to simulate reads
  force: false
  is_nfcore: true
  name: readsimulator
  org: nf-core
  outdir: .
  skip_features: null
  version: 1.0.1
update: null
